# For genes and varieties, there does not (yet) exist a reference vocabulary with a hierarchy.
# Such that there is no possible sub-concept for these entities.
# Therefore, this query searches for a simple mathc of an gene or variety, and returns a additional
# matchedEntities that only contains the searched entity, to be consistent with search for taxon or phenotypes/traits

PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX fabio:  <http://purl.org/spar/fabio/>
PREFIX frbr:   <http://purl.org/vocab/frbr/core#>
PREFIX oa:     <http://www.w3.org/ns/oa#>
PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?document ?title ?date ?publisher ?lang (group_concat(distinct ?author, "$") as ?authors) (group_concat(distinct ?matchedEntity, "$$") as ?matchedEntities)
FROM <http://ns.inria.fr/d2kab/graph/wheatgenomicsslkg>
WHERE {
    ?document a fabio:ResearchPaper.
    OPTIONAL { ?document dct:title ?title. FILTER isLiteral(?title) }
    OPTIONAL { ?document dct:creator ?author. }
    OPTIONAL { ?document dct:issued ?date. }
    OPTIONAL { ?document dct:source ?publisher. }
    OPTIONAL { ?document dct:language ?lang. }

    ?a oa:hasBody <{id}>; oa:hasTarget [ oa:hasSource ?source ].
    ?source frbr:partOf+ ?document.

    <{id}> skos:prefLabel ?entityLabel.
    BIND(concat("{id}", '$', ?entityLabel) as ?matchedEntity)

} group by ?document ?title ?date ?publisher ?lang limit 20000
