PREFIX dct:    <http://purl.org/dc/terms/>
PREFIX purl:    <http://purl.org/dc/elements/1.1/>
PREFIX fabio:  <http://purl.org/spar/fabio/>
PREFIX frbr:   <http://purl.org/vocab/frbr/core#>
PREFIX oa:     <http://www.w3.org/ns/oa#>

SELECT ?document ?title ?date ?publisher ?lang (group_concat(distinct ?author, "$") as ?authors)

FROM <http://ns.inria.fr/d2kab/graph/ricegenomicsslkg>
WHERE {
    ?document a fabio:ResearchPaper.
    OPTIONAL { ?document purl:title ?title. FILTER isLiteral(?title) }
    OPTIONAL { ?document purl:creator ?author. }
    OPTIONAL { ?document purl:issued ?date. }
    OPTIONAL { ?document purl:source ?publisher. }
    OPTIONAL { ?document purl:language ?lang. }

    {triples}

} group by ?document ?title ?date ?publisher ?lang limit 20000
